#! /bin/bash

# Installation Script 

repo="https://github.com/dramiajr/Arch-Setup.git"

error() {
  echo "[!] $1" >&2
  exit 1
}

header() {
  echo -e "\n*** $1 ***\n"
}

install_packages() {
  header "Installing packages..."
  sudo pacman -Syu --noconfirm || error "System update failed"
  sudo pacman -S --noconfirm \
    hyprland hyprpaper hypridle hyprlock \
    waybar kitty rofi emacs wlogout \
    python-pywal imagemagick \
    xdg-desktop-portal-hyprland \
    unzip wget base-devel \
    noto-fonts ttf-jetbrains-mono-nerd ttf-font-awesome \
    xdg-user-dirs xdg-utils || error "Package install failed"
}

clone_dotfiles() {
  header "Cloning dotfiles..."
  git clone --depth 1 "$repo" "$HOME/arch-setup" || error "Git clone failed"
}
